# Generated by Django 3.1 on 2020-08-12 17:03

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promo', '0001_initial'),
        ('users', '0003_auto_20200809_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.user')),
                ('note', models.IntegerField(blank=True, null=True)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promo.promo')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('users.user',),
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
