# Generated by Django 3.1 on 2020-08-26 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20200826_1248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invite',
            unique_together=set(),
        ),
    ]
