# Generated by Django 3.1 on 2020-08-26 10:58

from django.db import migrations, models
import django.db.models.deletion
import users.fields


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200826_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(default=users.fields.CurrentStudent, on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='students.student'),
        ),
    ]
