# Generated by Django 3.1 on 2020-08-26 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20200826_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='students.student'),
        ),
    ]
