# Generated by Django 3.0.8 on 2020-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(choices=[('CPI', 'CPI'), ('SC', 'SC')], max_length=50)),
                ('year', models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd')], max_length=50)),
                ('specialityName', models.CharField(blank=True, default='Main Branch', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('minTeamMembers', models.IntegerField(default=4)),
                ('maxTeamMembers', models.IntegerField(default=6)),
                ('maxTeamsInProject', models.IntegerField(default=2)),
            ],
            options={
                'unique_together': {('year', 'specialityName')},
            },
        ),
    ]
