# Generated by Django 3.2.8 on 2021-10-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promo',
            unique_together={('year', 'cycle')},
        ),
    ]
