# Generated by Django 3.1 on 2020-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('A', 'Accepted'), ('P', 'Pending'), ('R', 'Rejected')], default='P', max_length=8),
        ),
    ]
